-- Partie relationnelle

DROP TABLE COURSE;
DROP TABLE TEACHER;

-- Creation de la table TEACHER
-- Le NAME est la clef primaire et est donc NON NULL
CREATE TABLE TEACHER ( 
 NAME VARCHAR2(10) NOT NULL, 
 GRADE VARCHAR2 (10),
 CONSTRAINT PK_TEACHER PRIMARY KEY (NAME)
);
 
-- Insertion de valeurs pour TEACHER
INSERT INTO TEACHER VALUES('BERNARD', 'PROFESSEUR');
INSERT INTO TEACHER VALUES('LIU', 'ASSOCIE');
INSERT INTO TEACHER VALUES('LEMAIRE', 'STAGIAIRE');

-- Creation de la table COURSE
-- Le TITLE est la clef primaire et est donc NON NULL
-- C'est cette table qui a une clef etrangere car chaque cours depend d'un prof
CREATE TABLE COURSE ( 
 TITLE VARCHAR2(10) NOT NULL, 
 SEMESTER NUMBER(1),
 NAME VARCHAR2 (10),
 CONSTRAINT PK_COURSE PRIMARY KEY (TITLE),
 CONSTRAINT FK_COURSE_TEACHER FOREIGN KEY (NAME) REFERENCES TEACHER(NAME)
);

-- Insertion de valeurs pour COURSE
INSERT INTO COURSE VALUES('MATHS', 1, 'BERNARD');
INSERT INTO COURSE VALUES('FRENCH', 2, 'BERNARD');
INSERT INTO COURSE VALUES('ENGLISH', 3, 'LIU');
INSERT INTO COURSE VALUES('HISTORY', 2, 'LEMAIRE');
INSERT INTO COURSE VALUES('SPORT', 1, 'LIU');


-- Partie objet

CREATE TYPE COURSE_TYPE AS OBJECT (
 TITLE VARCHAR2(10), 
 SEMESTER NUMBER(1)
); 

CREATE TYPE COURSES_TYPE AS TABLE OF COURSE_TYPE;

CREATE TYPE TEACHER_TYPE AS OBJECT (
 NAME VARCHAR2(10), 
 GRADE VARCHAR2 (10),
 COURSES COURSES_TYPE
);

CREATE TABLE TEACHER_TABLE OF TEACHER_TYPE NESTED TABLE COURSES STORE AS COURSES_TABLE;

INSERT INTO TEACHER_TABLE VALUES (
    'BERNARD', 
    'PROFESSEUR',
    COURSES_TYPE(
        COURSE_TYPE('MATHS', 1),
        COURSE_TYPE('FRENCH', 2)
    )
);

INSERT INTO TEACHER_TABLE VALUES (
    'LIU', 
    'ASSOCIE',
    COURSES_TYPE(
        COURSE_TYPE('ENGLISH', 3),
        COURSE_TYPE('SPORT', 1)
    )
);

INSERT INTO TEACHER_TABLE VALUES (
    'LEMAIRE', 
    'STAGIAIRE',
    COURSES_TYPE(
        COURSE_TYPE('HISTORY', 2)
    )
);

ALTER TYPE TEACHER_TYPE ADD MEMBER FUNCTION NBCOURSES RETURN NUMBER;


CREATE OR REPLACE TYPE BODY TEACHER_TYPE AS
 MEMBER FUNCTION NBCOURSES RETURN NUMBER IS 
 NUMBERCOURSES NUMBER;
 BEGIN
    NUMBERCOURSES := COURSES.COUNT;
    RETURN NUMBERCOURSES;
 END;
END;



-- Names of the teachers who teach in semester X (relationnal)

SELECT TEACHER.NAME 
FROM TEACHER JOIN COURSE 
ON TEACHER.NAME = COURSE.NAME AND COURSE.SEMESTER = 1;


-- Semesters during which teacher Y teaches (relationnal)

SELECT SEMESTER
FROM COURSE JOIN TEACHER
ON COURSE.NAME = TEACHER.NAME
WHERE TEACHER.NAME = 'LIU';

-- Names of the teachers who teach in semester X (object)

SELECT DISTINCT T.NAME
FROM TEACHER_TABLE T,
    TABLE(T.COURSES) C
WHERE C.SEMESTER = 1;

-- Semesters during which teacher Y teaches (object)

SELECT DISTINCT C.SEMESTER
FROM TEACHER_TABLE T,
     TABLE(T.COURSES) C
WHERE T.NAME = 'LIU';